# https://hub.docker.com/r/ovrclk/akash/tags?page=1&ordering=last_updated
FROM osmosis-labs/bech32ibc:268bf838cb2fe6e58312cf0c1a8c6c19cb8dacbf

# Set up dependencies
ENV PACKAGES curl make git libc-dev bash gcc linux-headers eudev-dev python3

USER root

COPY ./bech32ibc-setup.sh .

COPY ./valkeys ./setup/valkeys

EXPOSE 26657

ENTRYPOINT [ "./bech32ibc-setup.sh" ]
# NOTE: to run this image, docker run -d -p 26657:26657 ./bech32ibc-setup.sh {{chain_id}} {{genesis_account}} {{seeds}} {{priv_validator_key_path}}
