name: Tests / Code Coverage
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to master & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - name: Display go version
        run: go version
      - name: Build docker instances
        run: make build-bech32ibc-docker
      - name: Run all tests
        run: make relay-test-bech32ibc
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2